// Get the variables from env
const { REACT_APP_API_ENDPOINT, REACT_APP_API_ENDPOINT_1 } = process.env;

// End Points
export const ENDPOINTS = {
  YCW: {
    GET_ALL: `${REACT_APP_API_ENDPOINT}user/worker/get/all/worker`,
    GET_BY_ID: `${REACT_APP_API_ENDPOINT}user/worker/get/details/`,
    GET_PROFILE: `${REACT_APP_API_ENDPOINT}/user/worker/profile/`,
  },
  CUSTOMER: {
    GET_ALL: `${REACT_APP_API_ENDPOINT}user/customer/get/all/customer`,
    GET_BY_ID: `${REACT_APP_API_ENDPOINT}user/customer/get/details/`,
    POST: `${REACT_APP_API_ENDPOINT}user/customer/save`,
  },
  JOBS: {
    GET: `${REACT_APP_API_ENDPOINT}user/job/get/all/job`,
    GET_BY_ID: `${REACT_APP_API_ENDPOINT}user/job/get/`,
    POST: `${REACT_APP_API_ENDPOINT}user/job/create`,
    POST_BY_AGE: `${REACT_APP_API_ENDPOINT}/job/create/agePreference`,
    DELETE: `${REACT_APP_API_ENDPOINT}/job/delete/`,
    PUT_BY_ID: `${REACT_APP_API_ENDPOINT}/job/get/`,
  },
  CITY: `${REACT_APP_API_ENDPOINT_1}locationmaster/city/get/all`,
  LOCALITY: `${REACT_APP_API_ENDPOINT_1}locationmaster/internal/micromarkets/all`,
  PROFILE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/profileStatus?flag=all`,
  SKILLS: `${REACT_APP_API_ENDPOINT}user/skill/get/skills`,
  USERS: `${REACT_APP_API_ENDPOINT}user/worker/search/user?searchTerm=`,
  SOURCE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/sourceChannel?flag=all`,
  RELIGION: `${REACT_APP_API_ENDPOINT}user/drop-down/get/religion`,
  MARITAL_STATUS: `${REACT_APP_API_ENDPOINT}user/drop-down/get/maritalStatus`,
  GENDER: `${REACT_APP_API_ENDPOINT}user/drop-down/get/gender`,
  COVID: `${REACT_APP_API_ENDPOINT}user/drop-down/get/covidVaccination`,
  EDUCATION: `${REACT_APP_API_ENDPOINT}user/drop-down/get/education`,
  CHECK_MOBILE: `${REACT_APP_API_ENDPOINT}user/worker/checkProfile/`,
  STATE_BY_ID: `${REACT_APP_API_ENDPOINT_1}locationmaster/state/get/states/by/`,
  CITY_BY_ID: `${REACT_APP_API_ENDPOINT_1}locationmaster/city/get/cities/by/`,
  MARKET_BY_ID: `${REACT_APP_API_ENDPOINT_1}locationmaster/internal/micromarket/list/`,
  PIN_CODE: `${REACT_APP_API_ENDPOINT}user/address/get/pincode/`,
  GET_ADDRESS: `${REACT_APP_API_ENDPOINT}user/address/get/`,
  SAVE_ADDRESS: `${REACT_APP_API_ENDPOINT}user/address/save`,
  DOCUMENT_TYPE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/documentUploadType?flag`,
  COUNTRY: `${REACT_APP_API_ENDPOINT_1}locationmaster/country/get/all`,
  DOCUMENT_CONTEXT: `${REACT_APP_API_ENDPOINT}user/drop-down/get/documentContext`,
  DOCUMENT: `${REACT_APP_API_ENDPOINT}user/document/all/`,
  DOCUMENT_UPLOAD: `${REACT_APP_API_ENDPOINT}user/document/upload`,
  FAMILY_MEMBER: `${REACT_APP_API_ENDPOINT}user/worker/familyMember`,
  GET_ADDRESS_BY_ID: `${REACT_APP_API_ENDPOINT}user/address/get/address/`,
  RELATION: `${REACT_APP_API_ENDPOINT}user/drop-down/get/relation`,
  BANK: `${REACT_APP_API_ENDPOINT}user/bank/`,
  GET_BANK: `${REACT_APP_API_ENDPOINT}user/bank/get/`,
  GET_BANK_DETAILS: `${REACT_APP_API_ENDPOINT}user/bank/get/bankDetails/`,
  GET_ACCOUNT_TYPE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/accountType`,
  GET_JOB: `${REACT_APP_API_ENDPOINT}user/worker/jobRequirement/`,
  TRAINING_MODE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/traningMode`,
  WORKING_HOURS: `${REACT_APP_API_ENDPOINT}user/drop-down/get/workingHours`,
  LEFT_JOB: `${REACT_APP_API_ENDPOINT}user/drop-down/get/reasonForLeftJob`,
  SKILL_BY_ID: `${REACT_APP_API_ENDPOINT}user/skill/`,
  SKILL_QUESTION: `${REACT_APP_API_ENDPOINT}user/skill/get/all/question?userId=`,
  SAVE_SKILL_USER_RESPONSE: `${REACT_APP_API_ENDPOINT}user/skill/save/userResponse`,
  SAVE_SKILL: `${REACT_APP_API_ENDPOINT}user/skill/save`,
  GET_LANGUAGE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/language?language`,
  UPDATE_PROFILE: `${REACT_APP_API_ENDPOINT}user/worker/profile/status/update`,
  JOBS_STATUS: `${REACT_APP_API_ENDPOINT}user/drop-down/get/jobStatus`,
  TRAINING_TYPE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/trainingType`,
  AGE_PREFERENCE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/agePreference`,
  PROFESSION: `${REACT_APP_API_ENDPOINT}user/drop-down/get/profession`,
  CX_SOURCE: `${REACT_APP_API_ENDPOINT}user/drop-down/get/sourceChannel?flag=customer`,
  USER_INTERNAL_ADD: `${REACT_APP_API_ENDPOINT}user/internal/add`,
  OCCUPATION: `${REACT_APP_API_ENDPOINT}user/drop-down/get/occupation`,
  LOCALITY_1: `${REACT_APP_API_ENDPOINT_1}locationmaster/micromarket/list`,

};
