export const data = [
  {
    id: 1,
    name: "Prescott Nerne",
    phone: "+86 400 702 4744",
    gender: "Male",
    city: "Daoqiao",
    skill: "Environmental Specialist",
    exp: 1,
    workHour: 9,
    jobs: 1,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 2,
    name: "Gilbert Gason",
    phone: "+46 230 250 9416",
    gender: "Male",
    city: "Haparanda",
    skill: "Operator",
    exp: 2,
    workHour: 23,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 3,
    name: "Margeaux Lansly",
    phone: "+356 497 491 2576",
    gender: "Agender",
    city: "Mosta",
    skill: "Statistician III",
    exp: 4,
    workHour: 8,
    jobs: 3,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 4,
    name: "Ario Ithell",
    phone: "+420 389 651 6600",
    gender: "Male",
    city: "Smidary",
    skill: "Nuclear Power Engineer",
    exp: 5,
    workHour: 8,
    jobs: 4,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 5,
    name: "Leoine Tapping",
    phone: "+502 725 160 2714",
    gender: "Female",
    city: "El Chol",
    skill: "Financial Advisor",
    exp: 2,
    workHour: 19,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 6,
    name: "Cristen Camerana",
    phone: "+260 313 546 9170",
    gender: "Female",
    city: "Mbala",
    skill: "Payment Adjustment Coordinator",
    exp: 3,
    workHour: 17,
    jobs: 2,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 7,
    name: "Minna Glowinski",
    phone: "+66 901 623 2133",
    gender: "Female",
    city: "Khon Kaen",
    skill: "Chemical Engineer",
    exp: 4,
    workHour: 15,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 8,
    name: "Obadiah Wibrew",
    phone: "+269 397 403 0357",
    gender: "Male",
    city: "Pajé",
    skill: "Executive Secretary",
    exp: 3,
    workHour: 20,
    jobs: 3,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 9,
    name: "Fabe Rawlins",
    phone: "+86 123 339 1090",
    gender: "Genderqueer",
    city: "Gexi",
    skill: "Chemical Engineer",
    exp: 3,
    workHour: 13,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 10,
    name: "Hastings Yeulet",
    phone: "+998 324 693 7899",
    gender: "Male",
    city: "Beruniy",
    skill: "Analyst Programmer",
    exp: 3,
    workHour: 11,
    jobs: 1,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 11,
    name: "Melantha Bonde",
    phone: "+221 551 336 7724",
    gender: "Female",
    city: "Ouro Sogui",
    skill: "Nuclear Power Engineer",
    exp: 3,
    workHour: 15,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 12,
    name: "Mariette Forst",
    phone: "+86 972 897 2087",
    gender: "Female",
    city: "Wengyang",
    skill: "Engineer IV",
    exp: 1,
    workHour: 9,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 13,
    name: "Martie MacDunlevy",
    phone: "+62 992 768 3434",
    gender: "Male",
    city: "Dasuk",
    skill: "Assistant Media Planner",
    exp: 3,
    workHour: 23,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 14,
    name: "Pail Beltzner",
    phone: "+45 897 508 1846",
    gender: "Male",
    city: "København",
    skill: "Biostatistician III",
    exp: 2,
    workHour: 12,
    jobs: 2,
    status: "INACTIVE",
  },
  {
    id: 15,
    name: "Sonia Janatka",
    phone: "+62 167 560 4060",
    gender: "Female",
    city: "Majan",
    skill: "Help Desk Operator",
    exp: 3,
    workHour: 18,
    jobs: 3,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 16,
    name: "Judie Tolchard",
    phone: "+62 383 945 2188",
    gender: "Female",
    city: "Desakolot",
    skill: "Senior Sales Associate",
    exp: 3,
    workHour: 11,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 17,
    name: "Rod Markos",
    phone: "+33 298 949 9836",
    gender: "Male",
    city: "Nice",
    skill: "Help Desk Operator",
    exp: 4,
    workHour: 22,
    jobs: 4,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 18,
    name: "Ursuline Exon",
    phone: "+51 590 970 2920",
    gender: "Female",
    city: "San Bernardino",
    skill: "Librarian",
    exp: 4,
    workHour: 13,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 19,
    name: "Kary Shuter",
    phone: "+385 412 837 5860",
    gender: "Female",
    city: "Bršadin",
    skill: "Web Designer II",
    exp: 3,
    workHour: 12,
    jobs: 2,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 20,
    name: "Devlin Powney",
    phone: "+358 884 122 9059",
    gender: "Male",
    city: "Kiuruvesi",
    skill: "Human Resources Assistant III",
    exp: 1,
    workHour: 9,
    jobs: 2,
    status: "INACTIVE",
  },
  {
    id: 21,
    name: "Renato Dudhill",
    phone: "+220 327 946 1810",
    gender: "Male",
    city: "Sabi",
    skill: "Physical Therapy Assistant",
    exp: 4,
    workHour: 14,
    jobs: 2,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 22,
    name: "Alix Meechan",
    phone: "+7 378 411 9897",
    gender: "Male",
    city: "Shchelkovo",
    skill: "Information Systems Manager",
    exp: 1,
    workHour: 16,
    jobs: 4,
    status: "INACTIVE",
  },
  {
    id: 23,
    name: "Benjie Weigh",
    phone: "+27 456 643 5873",
    gender: "Male",
    city: "Volksrust",
    skill: "Structural Analysis Engineer",
    exp: 2,
    workHour: 15,
    jobs: 1,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 24,
    name: "Hervey Comoletti",
    phone: "+86 936 971 1360",
    gender: "Male",
    city: "Bailianhe",
    skill: "Technical Writer",
    exp: 3,
    workHour: 13,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 25,
    name: "Tyson Maceur",
    phone: "+86 610 875 2297",
    gender: "Male",
    city: "Muqi",
    skill: "Research Associate",
    exp: 4,
    workHour: 16,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 26,
    name: "Franz Tummons",
    phone: "+86 340 755 6463",
    gender: "Male",
    city: "Jiuchi",
    skill: "Geological Engineer",
    exp: 4,
    workHour: 18,
    jobs: 3,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 27,
    name: "Randolf Gaskin",
    phone: "+86 666 204 7301",
    gender: "Male",
    city: "Taihua",
    skill: "Business Systems Development Analyst",
    exp: 3,
    workHour: 14,
    jobs: 3,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 28,
    name: "Klement Phlipon",
    phone: "+86 106 310 0500",
    gender: "Male",
    city: "Zhijin",
    skill: "Web Developer IV",
    exp: 3,
    workHour: 21,
    jobs: 2,
    status: "INACTIVE",
  },
  {
    id: 29,
    name: "Edithe Steptowe",
    phone: "+7 935 430 9647",
    gender: "Female",
    city: "Voloshka",
    skill: "Programmer Analyst II",
    exp: 5,
    workHour: 14,
    jobs: 4,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 30,
    name: "Lindy Northleigh",
    phone: "+62 152 780 4208",
    gender: "Male",
    city: "Palamadu",
    skill: "Assistant Manager",
    exp: 1,
    workHour: 16,
    jobs: 4,
    status: "INACTIVE",
  },
  {
    id: 31,
    name: "Florry Thomazet",
    phone: "+420 142 427 0669",
    gender: "Female",
    city: "Hluboká nad Vltavou",
    skill: "Accounting Assistant III",
    exp: 5,
    workHour: 9,
    jobs: 1,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 32,
    name: "Aube Sherrett",
    phone: "+86 880 393 9635",
    gender: "Male",
    city: "Jingling",
    skill: "Chief Design Engineer",
    exp: 3,
    workHour: 23,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 33,
    name: "Cathrin Muge",
    phone: "+351 375 149 1088",
    gender: "Female",
    city: "Horta",
    skill: "Recruiter",
    exp: 5,
    workHour: 17,
    jobs: 3,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 34,
    name: "Alexa Coltman",
    phone: "+81 305 704 9030",
    gender: "Female",
    city: "Narutō",
    skill: "Occupational Therapist",
    exp: 4,
    workHour: 14,
    jobs: 1,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 35,
    name: "Jeanie Baiyle",
    phone: "+46 371 565 7455",
    gender: "Female",
    city: "Burträsk",
    skill: "Recruiting Manager",
    exp: 4,
    workHour: 18,
    jobs: 4,
    status: "INACTIVE",
  },
  {
    id: 36,
    name: "Yettie Hulme",
    phone: "+7 633 475 3255",
    gender: "Polygender",
    city: "Uk",
    skill: "Systems Administrator III",
    exp: 5,
    workHour: 23,
    jobs: 1,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 37,
    name: "Crysta Moyer",
    phone: "+1 562 221 8336",
    gender: "Female",
    city: "Saint-Bruno",
    skill: "Civil Engineer",
    exp: 4,
    workHour: 24,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 38,
    name: "Richart Rois",
    phone: "+62 603 189 2024",
    gender: "Male",
    city: "Dukuh",
    skill: "Statistician II",
    exp: 5,
    workHour: 18,
    jobs: 3,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 39,
    name: "Diarmid Muslim",
    phone: "+86 731 290 4207",
    gender: "Male",
    city: "Jingzhou",
    skill: "Product Engineer",
    exp: 1,
    workHour: 24,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 40,
    name: "Reginauld Whittet",
    phone: "+216 745 756 3221",
    gender: "Male",
    city: "Skhira",
    skill: "Paralegal",
    exp: 4,
    workHour: 9,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 41,
    name: "Charmian Lief",
    phone: "+48 387 374 8146",
    gender: "Female",
    city: "Skrzyszów",
    skill: "VP Product Management",
    exp: 4,
    workHour: 20,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 42,
    name: "Gray Aird",
    phone: "+7 274 341 0240",
    gender: "Male",
    city: "Kurumoch",
    skill: "Nuclear Power Engineer",
    exp: 2,
    workHour: 21,
    jobs: 2,
    status: "INACTIVE",
  },
  {
    id: 43,
    name: "Jaime Calterone",
    phone: "+62 337 449 5095",
    gender: "Female",
    city: "Sungaiduri",
    skill: "Administrative Officer",
    exp: 5,
    workHour: 8,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 44,
    name: "Erin MacQuist",
    phone: "+86 988 236 7361",
    gender: "Male",
    city: "Zhouzai",
    skill: "Environmental Tech",
    exp: 5,
    workHour: 11,
    jobs: 3,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 45,
    name: "Putnem Pudden",
    phone: "+970 205 779 9326",
    gender: "Male",
    city: "Far‘ūn",
    skill: "Dental Hygienist",
    exp: 2,
    workHour: 19,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 46,
    name: "Charlene Stearne",
    phone: "+351 995 785 5992",
    gender: "Female",
    city: "Zibreira",
    skill: "Sales Representative",
    exp: 2,
    workHour: 17,
    jobs: 4,
    status: "INACTIVE",
  },
  {
    id: 47,
    name: "Noll Rebillard",
    phone: "+54 205 166 2529",
    gender: "Male",
    city: "Colonia Elisa",
    skill: "Administrative Assistant III",
    exp: 1,
    workHour: 9,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 48,
    name: "Noble Jerzycowski",
    phone: "+386 752 348 9402",
    gender: "Male",
    city: "Celje",
    skill: "Teacher",
    exp: 4,
    workHour: 10,
    jobs: 4,
    status: "INACTIVE",
  },
  {
    id: 49,
    name: "Irv Holde",
    phone: "+963 457 787 9955",
    gender: "Male",
    city: "Kafr Takhārīm",
    skill: "Mechanical Systems Engineer",
    exp: 1,
    workHour: 16,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 50,
    name: "Maryellen Gumly",
    phone: "+86 823 241 5310",
    gender: "Female",
    city: "Zhoutou",
    skill: "Programmer II",
    exp: 3,
    workHour: 20,
    jobs: 2,
    status: "ACTIVE & UNAVAILABLE",
  },
];

export const customer = [
  {
    id: 1,
    name: "Indu Modi",
    phone: "9869225464",
    Email: "indu@gmail.com",
    location: "Haryana",
    openJobs: 4,
    activeJobs: 9,
    status: "ACTIVE",
  },

  {
    id: 1,
    name: "Kiran Reddy",
    phone: "9869225464",
    Email: "kiran@gmail.com",
    location: "Haryana",
    openJobs: 4,
    activeJobs: 9,
    status: "INACTIVE",
  },

  {
    id: 1,
    name: "Khusboo",
    phone: "9869225464",
    Email: "Khusboo@gmail.com",
    location: "Haryana",
    openJobs: 4,
    activeJobs: 9,
    status: "WAITING",
  },
];

export const jobData = [
  {
    id: "1",
    jobType: "HK",
    customerId: "5",
    location: "Haryana",
    Duration: "8Hours",
    BudgetRange: "10k-12k",
    startDate: "5july2022",
    highestActiveStage: "interview sheduling pending",
    status: "IN PROGRESS",
  },

  {
    id: "2",
    jobType: "HK",
    customerId: "5",
    location: "Haryana",
    Duration: "8Hours",
    BudgetRange: "10k-12k",
    startDate: "5july2022",
    highestActiveStage: "interview sheduling pending",
    status: "INACTIVE",
  },
  {
    id: "3",
    jobType: "HK",
    customerId: "5",
    location: "Haryana",
    Duration: "8Hours",
    BudgetRange: "10k-12k",
    startDate: "5july2022",
    highestActiveStage: "interview sheduling pending",
    status: "ACTIVE",
  },
];
