export const data = [
  {
    id: 1,
    name: "Prescott Nerne",
    phone: "+86 400 702 4744",
    gender: "Male",
    city: "Daoqiao",
    skill: "Environmental Specialist",
    exp: 1,
    workHour: 9,
    jobs: 1,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 2,
    name: "Gilbert Gason",
    phone: "+46 230 250 9416",
    gender: "Male",
    city: "Haparanda",
    skill: "Operator",
    exp: 2,
    workHour: 23,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 3,
    name: "Margeaux Lansly",
    phone: "+356 497 491 2576",
    gender: "Agender",
    city: "Mosta",
    skill: "Statistician III",
    exp: 4,
    workHour: 8,
    jobs: 3,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 4,
    name: "Ario Ithell",
    phone: "+420 389 651 6600",
    gender: "Male",
    city: "Smidary",
    skill: "Nuclear Power Engineer",
    exp: 5,
    workHour: 8,
    jobs: 4,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 5,
    name: "Leoine Tapping",
    phone: "+502 725 160 2714",
    gender: "Female",
    city: "El Chol",
    skill: "Financial Advisor",
    exp: 2,
    workHour: 19,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 6,
    name: "Cristen Camerana",
    phone: "+260 313 546 9170",
    gender: "Female",
    city: "Mbala",
    skill: "Payment Adjustment Coordinator",
    exp: 3,
    workHour: 17,
    jobs: 2,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 7,
    name: "Minna Glowinski",
    phone: "+66 901 623 2133",
    gender: "Female",
    city: "Khon Kaen",
    skill: "Chemical Engineer",
    exp: 4,
    workHour: 15,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
  {
    id: 8,
    name: "Obadiah Wibrew",
    phone: "+269 397 403 0357",
    gender: "Male",
    city: "Pajé",
    skill: "Executive Secretary",
    exp: 3,
    workHour: 20,
    jobs: 3,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 9,
    name: "Fabe Rawlins",
    phone: "+86 123 339 1090",
    gender: "Genderqueer",
    city: "Gexi",
    skill: "Chemical Engineer",
    exp: 3,
    workHour: 13,
    jobs: 3,
    status: "INACTIVE",
  },
  {
    id: 10,
    name: "Hastings Yeulet",
    phone: "+998 324 693 7899",
    gender: "Male",
    city: "Beruniy",
    skill: "Analyst Programmer",
    exp: 3,
    workHour: 11,
    jobs: 1,
    status: "ACTIVE & AVAILABLE",
  },
  {
    id: 11,
    name: "Melantha Bonde",
    phone: "+221 551 336 7724",
    gender: "Female",
    city: "Ouro Sogui",
    skill: "Nuclear Power Engineer",
    exp: 3,
    workHour: 15,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 12,
    name: "Mariette Forst",
    phone: "+86 972 897 2087",
    gender: "Female",
    city: "Wengyang",
    skill: "Engineer IV",
    exp: 1,
    workHour: 9,
    jobs: 1,
    status: "INACTIVE",
  },
  {
    id: 13,
    name: "Martie MacDunlevy",
    phone: "+62 992 768 3434",
    gender: "Male",
    city: "Dasuk",
    skill: "Assistant Media Planner",
    exp: 3,
    workHour: 23,
    jobs: 4,
    status: "ACTIVE & UNAVAILABLE",
  },
];

export const customer = [
  {
    id: 1,
    name: "Indu Modi",
    phone: "9869225464",
    Email: "indu@gmail.com",
    location: "Haryana",
    openJobs: 4,
    activeJobs: 9,
    status: "ACTIVE",
  },
  {
    id: 1,
    name: "Kiran Reddy",
    phone: "9869225464",
    Email: "kiran@gmail.com",
    location: "Haryana",
    openJobs: 4,
    activeJobs: 9,
    status: "INACTIVE",
  },
  {
    id: 1,
    name: "Khusboo",
    phone: "9869225464",
    Email: "Khusboo@gmail.com",
    location: "Haryana",
    openJobs: 4,
    activeJobs: 9,
    status: "WAITING",
  },
];
export const jobData = [
  {
    id: "1",
    jobType: "HK",
    customerId: "5",
    location: "Haryana",
    Duration: "8Hours",
    BudgetRange: "10k-12k",
    startDate: "5july2022",
    highestActiveStage: "interview sheduling pending",
    status: "IN PROGRESS",
  },
  {
    id: "2",
    jobType: "HK",
    customerId: "5",
    location: "Haryana",
    Duration: "8Hours",
    BudgetRange: "10k-12k",
    startDate: "5july2022",
    highestActiveStage: "interview sheduling pending",
    status: "INACTIVE",
  },
  {
    id: "3",
    jobType: "HK",
    customerId: "5",
    location: "Haryana",
    Duration: "8Hours",
    BudgetRange: "10k-12k",
    startDate: "5july2022",
    highestActiveStage: "interview sheduling pending",
    status: "ACTIVE",
  },
];

export const steps = [
  "Applied",
  "Shortlisted",
  "Interview Schduled",
  "CX Interview",
  "Trial Scheduled",
  "In-House Trail",
  "CX House Trial",
  "Contract Generation",
  "Contract Signing CX",
  "Contract Signing YCW",
  "Job Started",
];




const newData = [
  {
    data: [
      {
        userId: "YCW0000014",
        name: "abc abc abc",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "abc",
        totalExperience: "2",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "a@gmail.com",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000001",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: "Agra",
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000002",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: "Agra",
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000003",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000004",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000015",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000016",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000024",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000027",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000028",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000029",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000038",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
      {
        userId: "YCW0000039",
        name: "string string string",
        gender: { key: "MALE", value: "Male" },
        mobileNo: "string",
        totalExperience: "string",
        profileStatus: {
          key: "ACTIVE_AND_NOT_AVAILABLE",
          value: "ACTIVE & NOT AVAILABLE",
        },
        skill: "Driving (P), Driving , Driving",
        cityName: null,
        email: "string",
        workingHours: { key: "_0_TO_2_HOURS", value: "0 to 2 hr" },
      },
    ],
  },
];
